export const DEMO_FERRARI = {
  car: {
    make: "Ferrari", model: "458 Italia", year: 2012, trim: "Base",
    bodyStyle: "Mid-engine coupe", engine: "4.5L Naturally Aspirated V8",
    horsepower: 562, torque: "398 lb-ft", transmission: "7-speed dual-clutch F1",
    drivetrain: "RWD", productionYears: "2009–2015", msrpOriginal: "$229,825"
  },
  parts: [
    { id:"p1", category:"Engine", name:"Engine Assembly (F136 V8)", partNumber:"FER-136-458-ASM", description:"Complete 4.5L naturally aspirated V8 unit producing 562hp at 9,000rpm. Ferrari's finest naturally aspirated road car engine, featuring flat-plane crankshaft and individual throttle bodies.", priceMin:48000, priceMax:78000, sources:[{name:"Ferrari of Newport Beach",type:"OEM Dealer",priceEstimate:78000},{name:"Forza Motorsport Parts",type:"Independent",priceEstimate:54000},{name:"Symbolic Motors (Used)",type:"Used/OEM",priceEstimate:48000}], availability:"Special Order", difficulty:"Professional Required", laborHours:24 },
    { id:"p2", category:"Brakes", name:"Carbon Ceramic Brake Disc (Front)", partNumber:"FER-CCM-458-F", description:"Brembo carbon-ceramic front disc measuring 398mm. Provides exceptional stopping power with dramatically reduced unsprung weight compared to cast iron.", priceMin:3200, priceMax:5800, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:5800},{name:"Brembo Direct",type:"Independent",priceEstimate:4100},{name:"eBay Motors",type:"Used/OEM",priceEstimate:3200}], availability:"Limited", difficulty:"Professional Required", laborHours:4 },
    { id:"p3", category:"Suspension", name:"Magnetorheological Shock Absorber", partNumber:"FER-MR-458-SH", description:"Magneti Marelli magnetorheological damper unit for the Manettino-controlled suspension system. Adjusts damping in real-time based on road conditions.", priceMin:1800, priceMax:3400, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:3400},{name:"Ricambi America",type:"Independent",priceEstimate:2200},{name:"Used Import",type:"Used/OEM",priceEstimate:1800}], availability:"Special Order", difficulty:"Professional Required", laborHours:3 },
    { id:"p4", category:"Exhaust", name:"Inconel Exhaust Manifold", partNumber:"FER-EXH-458-MAN", description:"Lightweight Inconel alloy exhaust manifold responsible for the 458's iconic high-revving exhaust note. Feeds the twin catalytic converters.", priceMin:4200, priceMax:7500, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:7500},{name:"Capristo Exhausts",type:"Aftermarket",priceEstimate:5200},{name:"Forza Parts",type:"Used/OEM",priceEstimate:4200}], availability:"Special Order", difficulty:"Professional Required", laborHours:6 },
    { id:"p5", category:"Drivetrain", name:"F1 Dual-Clutch Gearbox", partNumber:"FER-DCT-458-GBX", description:"7-speed dual-clutch transmission capable of shifting in 60 milliseconds. Rear-mounted for optimal weight distribution as a transaxle unit.", priceMin:22000, priceMax:38000, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:38000},{name:"GP Motor Works",type:"Independent",priceEstimate:26000},{name:"Salvage Unit",type:"Used/OEM",priceEstimate:22000}], availability:"Special Order", difficulty:"Professional Required", laborHours:18 },
    { id:"p6", category:"Cooling", name:"Engine Radiator (Centre)", partNumber:"FER-RAD-458-CTR", description:"Central aluminium radiator in the tri-radiator cooling system. Works with two side-mounted units to maintain optimal operating temperature.", priceMin:1400, priceMax:2800, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:2800},{name:"Mishimoto",type:"Aftermarket",priceEstimate:1900},{name:"Ricambi America",type:"Independent",priceEstimate:1400}], availability:"In Stock", difficulty:"Professional Required", laborHours:5 },
    { id:"p7", category:"Body", name:"Front Bumper Assembly", partNumber:"FER-BMP-458-FR", description:"Full carbon fibre or fibreglass front bumper assembly including integrated splitter and air ducts. Pininfarina-designed aerodynamic bodywork.", priceMin:3800, priceMax:9200, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:9200},{name:"Carbon Revolution",type:"Aftermarket",priceEstimate:5400},{name:"Used OEM",type:"Used/OEM",priceEstimate:3800}], availability:"Limited", difficulty:"Moderate", laborHours:3 },
    { id:"p8", category:"Electrical", name:"ECU (Engine Control Unit)", partNumber:"FER-ECU-458-MG", description:"Magneti Marelli engine management ECU controlling fuel injection, ignition timing, and traction control. Must be programmed to matching VIN.", priceMin:2800, priceMax:5500, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:5500},{name:"SpeedFactory",type:"Independent",priceEstimate:3600},{name:"Used/Coded",type:"Used/OEM",priceEstimate:2800}], availability:"Special Order", difficulty:"Professional Required", laborHours:2 },
    { id:"p9", category:"Interior", name:"Carbon Fibre Racing Seat (Driver)", partNumber:"FER-SEAT-458-CF", description:"Lightweight carbon fibre bucket seat with Alcantara trim and integrated seat belt guide. Available in multiple configurations including full racing spec.", priceMin:4500, priceMax:8800, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:8800},{name:"Sabelt Direct",type:"Independent",priceEstimate:5900},{name:"Ferrari Exchange",type:"Used/OEM",priceEstimate:4500}], availability:"Limited", difficulty:"DIY Friendly", laborHours:1 },
    { id:"p10", category:"Engine", name:"Throttle Body Set (8 units)", partNumber:"FER-TB-458-SET8", description:"Full set of 8 individual throttle bodies for the V8, one per cylinder. Critical for the engine's linear power delivery and high-revving character.", priceMin:2200, priceMax:4100, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:4100},{name:"Caprari Motorsport",type:"Independent",priceEstimate:2900},{name:"Used OEM Set",type:"Used/OEM",priceEstimate:2200}], availability:"Limited", difficulty:"Professional Required", laborHours:8 },
    { id:"p11", category:"Brakes", name:"Brake Caliper (Front, Yellow)", partNumber:"FER-CAL-458-FY", description:"Brembo 6-piston front brake caliper in signature Ferrari yellow. Paired with the 398mm CCM discs for exceptional heat dissipation.", priceMin:1600, priceMax:3200, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:3200},{name:"Brembo OEM",type:"Independent",priceEstimate:2100},{name:"Used Pull",type:"Used/OEM",priceEstimate:1600}], availability:"In Stock", difficulty:"Moderate", laborHours:2 },
    { id:"p12", category:"Suspension", name:"Front Control Arm (Upper)", partNumber:"FER-CTL-458-UF", description:"Aluminium double-wishbone upper control arm for the front suspension. Lightweight forged construction for precise steering response.", priceMin:680, priceMax:1400, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:1400},{name:"Ricambi America",type:"Independent",priceEstimate:920},{name:"Used OEM",type:"Used/OEM",priceEstimate:680}], availability:"In Stock", difficulty:"Professional Required", laborHours:3 },
    { id:"p13", category:"Drivetrain", name:"Limited Slip Differential (E-Diff)", partNumber:"FER-EDIFF-458", description:"Ferrari's electronic limited slip differential managed by the Vehicle Dynamic Control system. Provides torque vectoring for optimal traction out of corners.", priceMin:5800, priceMax:11000, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:11000},{name:"GP Works",type:"Independent",priceEstimate:7400},{name:"Used Unit",type:"Used/OEM",priceEstimate:5800}], availability:"Special Order", difficulty:"Professional Required", laborHours:10 },
    { id:"p14", category:"Exhaust", name:"Sport Exhaust Valve Actuator", partNumber:"FER-EXV-458-ACT", description:"Electronically controlled exhaust bypass valve that opens at high RPM for the full 458 exhaust note. Controlled via the Manettino switch.", priceMin:420, priceMax:890, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:890},{name:"Ricambi America",type:"Independent",priceEstimate:580},{name:"Used Part",type:"Used/OEM",priceEstimate:420}], availability:"In Stock", difficulty:"Moderate", laborHours:1 },
    { id:"p15", category:"Electrical", name:"Manettino Steering Wheel Switch", partNumber:"FER-MAN-458-SW", description:"The iconic five-position Manettino dial on the steering wheel controlling suspension, traction control, and exhaust modes. Wet, Sport, Race, CT Off, ESC Off.", priceMin:380, priceMax:820, sources:[{name:"Ferrari Dealer",type:"OEM Dealer",priceEstimate:820},{name:"Euro Car Parts",type:"Independent",priceEstimate:520},{name:"Used Wheel Part",type:"Used/OEM",priceEstimate:380}], availability:"In Stock", difficulty:"Moderate", laborHours:1 }
  ],
  faults: [
    { id:"f1", severity:"Critical", title:"HELE System Fuel Pump Failure", description:"The High Emotion Low Emission stop-start system's fuel pump is known to fail prematurely, leaving the car stranded. Ferrari issued a technical service bulletin but no formal recall.", affectedYears:"2010–2013", frequency:"Common", symptoms:["Engine fails to restart after stop-start shutdown","Long cranking before start","Fuel pressure warning on dashboard","Engine cuts out at low speed"], repairCostMin:1800, repairCostMax:3500, diyPossible:false, preventionTip:"Disable the HELE system via the centre console button on every drive until the pump is replaced with the updated part." },
    { id:"f2", severity:"High", title:"Sticky Interior Plastics & Leather Degradation", description:"The soft-touch dashboard and interior trim plastics become sticky and degrade over time due to the chemical composition of the coating used. Affects nearly all early cars.", affectedYears:"2009–2012", frequency:"Very Common", symptoms:["Sticky tacky feel on dashboard surfaces","Black residue transferring to hands","Leather bolsters cracking prematurely","Peeling trim around air vents"], repairCostMin:3500, repairCostMax:12000, diyPossible:false, preventionTip:"Keep the car garaged and use UV-protective interior dressing regularly. Budget for a full interior refresh on cars over 8 years old." },
    { id:"f3", severity:"High", title:"Carbon Ceramic Brake Disc Cracking", description:"The CCM brake discs can develop radial cracks if subjected to cold weather braking or if bedded in improperly. Cracked discs must be replaced immediately.", affectedYears:"2009–2015", frequency:"Occasional", symptoms:["Visible cracks radiating from centre bell","Vibration under heavy braking","Grinding noise at low speed","Uneven brake pedal feel"], repairCostMin:6400, repairCostMax:18000, diyPossible:false, preventionTip:"Always warm up the brakes gently for the first 5 minutes of driving, especially in cold weather. Inspect discs visually every 6 months." },
    { id:"f4", severity:"Medium", title:"Power Steering Pump Leak", description:"The electrically-assisted power steering pump develops seal leaks around 30,000–50,000 miles. The leak contaminates the subframe area and can cause steering assistance to fail.", affectedYears:"2009–2014", frequency:"Common", symptoms:["Power steering fluid puddle under front of car","Groaning noise when turning at low speed","Increased steering effort","Low fluid warning light"], repairCostMin:900, repairCostMax:2200, diyPossible:false, preventionTip:"Check power steering fluid level monthly and inspect the pump area for early signs of seepage at every service." },
    { id:"f5", severity:"Medium", title:"Stone Chip & Underbody Damage", description:"The 458's extremely low ride height and flat carbon composite underbody panels are highly susceptible to stone chip damage and scraping on speed bumps or steep driveways.", affectedYears:"2009–2015", frequency:"Very Common", symptoms:["Visible stone chips on lower bumper and sills","Scraping noise over uneven surfaces","Cracked or broken undertray panels","Water ingress into undertray cavity"], repairCostMin:400, repairCostMax:4500, diyPossible:true, preventionTip:"Apply clear paint protection film to the front bumper, sills, and undertray edges. Use a car ramp when approaching steep driveways." },
    { id:"f6", severity:"Low", title:"Rear Window Delamination", description:"The polycarbonate rear engine cover window can delaminate and turn yellow or hazy over time due to UV exposure. This is cosmetic but significantly affects the visual appeal.", affectedYears:"2009–2013", frequency:"Occasional", symptoms:["Yellowing or cloudiness of rear window","Bubbling between polycarbonate layers","Visible delamination edges","Engine bay less visible from exterior"], repairCostMin:800, repairCostMax:2400, diyPossible:false, preventionTip:"Apply UV-resistant polycarbonate coating annually and store the car away from direct sunlight when not in use." }
  ]
};

export const DEMO_PORSCHE = {
  car: {
    make: "Porsche", model: "911 GT3 RS", year: 2023, trim: "GT3 RS",
    bodyStyle: "Rear-engine coupe", engine: "4.0L Naturally Aspirated Flat-6",
    horsepower: 518, torque: "343 lb-ft", transmission: "7-speed PDK",
    drivetrain: "RWD", productionYears: "2022–present", msrpOriginal: "$223,800"
  },
  parts: [
    { id:"p1", category:"Engine", name:"Flat-6 Engine Assembly (9A2 GT3)", partNumber:"POR-9A2-GT3-ASM", description:"4.0L naturally aspirated flat-six revving to 9,000rpm. Derived directly from Porsche Motorsport racing engines with titanium connecting rods.", priceMin:52000, priceMax:85000, sources:[{name:"Porsche Dealer",type:"OEM Dealer",priceEstimate:85000},{name:"Porsche Exchange",type:"Independent",priceEstimate:62000},{name:"Used Unit",type:"Used/OEM",priceEstimate:52000}], availability:"Special Order", difficulty:"Professional Required", laborHours:22 },
    { id:"p2", category:"Brakes", name:"PCCB Carbon Ceramic Front Disc", partNumber:"POR-PCCB-GT3-F", description:"Porsche Carbon Composite Brake 408mm front disc. Reduces unsprung weight by 50% vs iron and provides consistent stopping from any speed.", priceMin:2800, priceMax:5200, sources:[{name:"Porsche Dealer",type:"OEM Dealer",priceEstimate:5200},{name:"Brembo OEM",type:"Independent",priceEstimate:3600},{name:"Used Pull",type:"Used/OEM",priceEstimate:2800}], availability:"Limited", difficulty:"Professional Required", laborHours:4 },
    { id:"p3", category:"Suspension", name:"Rear Wing DRS Actuator", partNumber:"POR-DRS-GT3RS-ACT", description:"Drag Reduction System actuator for the massive swan-neck rear wing. Opens the wing flap under braking for increased downforce.", priceMin:1200, priceMax:2600, sources:[{name:"Porsche Dealer",type:"OEM Dealer",priceEstimate:2600},{name:"GT Motorsport",type:"Independent",priceEstimate:1700},{name:"Used Part",type:"Used/OEM",priceEstimate:1200}], availability:"Special Order", difficulty:"Professional Required", laborHours:3 },
    { id:"p4", category:"Exhaust", name:"Titanium Exhaust System", partNumber:"POR-TI-GT3RS-EXH", description:"Full titanium exhaust system saving 17kg over standard steel. Produces the GT3 RS's distinctive high-pitch flat-six howl at the 9,000rpm limiter.", priceMin:6800, priceMax:12000, sources:[{name:"Porsche Dealer",type:"OEM Dealer",priceEstimate:12000},{name:"Akrapovic",type:"Aftermarket",priceEstimate:8400},{name:"Used OEM",type:"Used/OEM",priceEstimate:6800}], availability:"Limited", difficulty:"Professional Required", laborHours:5 },
    { id:"p5", category:"Drivetrain", name:"7-Speed PDK Gearbox", partNumber:"POR-PDK-GT3RS-7", description:"Porsche Doppelkupplung dual-clutch transmission tuned for the GT3 RS with shorter gear ratios. Shifts in under 100 milliseconds.", priceMin:18000, priceMax:32000, sources:[{name:"Porsche Dealer",type:"OEM Dealer",priceEstimate:32000},{name:"Autofarm",type:"Independent",priceEstimate:22000},{name:"Exchange Unit",type:"Used/OEM",priceEstimate:18000}], availability:"Special Order", difficulty:"Professional Required", laborHours:16 },
    { id:"p6", category:"Cooling", name:"Front Radiator (Centre)", partNumber:"POR-RAD-GT3RS-C", description:"Central front-mounted radiator in the 3-radiator cooling system. Works with side units to manage the high heat output of the track-focused engine.", priceMin:980, priceMax:2100, sources:[{name:"Porsche Dealer",type:"OEM Dealer",priceEstimate:2100},{name:"Mishimoto",type:"Aftermarket",priceEstimate:1400},{name:"Used OEM",type:"Used/OEM",priceEstimate:980}], availability:"In Stock", difficulty:"Professional Required", laborHours:4 },
    { id:"p7", category:"Body", name:"Carbon Fibre Front Bonnet", partNumber:"POR-CF-GT3RS-HOOD", description:"Full dry carbon fibre bonnet with integrated cooling vents. Saves 8kg over steel and forms part of the GT3 RS aero package.", priceMin:4200, priceMax:8800, sources:[{name:"Porsche Dealer",type:"OEM Dealer",priceEstimate:8800},{name:"Carbon Works",type:"Aftermarket",priceEstimate:5600},{name:"Used OEM",type:"Used/OEM",priceEstimate:4200}], availability:"Limited", difficulty:"Professional Required", laborHours:2 },
    { id:"p8", category:"Electrical", name:"PDK Control Module", partNumber:"POR-TCU-GT3RS-PDK", description:"Transmission control unit managing PDK shift points, launch control, and throttle blip on downshifts. Must be coded to vehicle.", priceMin:2400, priceMax:4800, sources:[{name:"Porsche Dealer",type:"OEM Dealer",priceEstimate:4800},{name:"IndyPorsche",type:"Independent",priceEstimate:3200},{name:"Used Coded",type:"Used/OEM",priceEstimate:2400}], availability:"Special Order", difficulty:"Professional Required", laborHours:2 },
    { id:"p9", category:"Interior", name:"Full Bucket Seat (Carbon)", partNumber:"POR-SEAT-GT3RS-CF", description:"Full carbon fibre racing seat with 4-point harness compatibility. FIA approved for track use and saves 14kg per seat vs standard sports seats.", priceMin:5200, priceMax:9400, sources:[{name:"Porsche Dealer",type:"OEM Dealer",priceEstimate:9400},{name:"Recaro Direct",type:"Independent",priceEstimate:6800},{name:"Used OEM",type:"Used/OEM",priceEstimate:5200}], availability:"Limited", difficulty:"DIY Friendly", laborHours:1 },
    { id:"p10", category:"Suspension", name:"Front Pushrod Damper Unit", partNumber:"POR-PUSH-GT3RS-F", description:"Front pushrod suspension damper unit — a motorsport-derived setup lowering the centre of gravity for improved handling not found on any other production 911.", priceMin:1800, priceMax:3600, sources:[{name:"Porsche Dealer",type:"OEM Dealer",priceEstimate:3600},{name:"Bilstein OEM",type:"Independent",priceEstimate:2400},{name:"Used Unit",type:"Used/OEM",priceEstimate:1800}], availability:"Special Order", difficulty:"Professional Required", laborHours:5 }
  ],
  faults: [
    { id:"f1", severity:"High", title:"PDK Software Hesitation in Sport Mode", description:"Some 2023 GT3 RS owners report a brief hesitation when downshifting aggressively in Sport mode. Porsche has released software updates addressing this.", affectedYears:"2022–2023", frequency:"Occasional", symptoms:["Brief pause during aggressive downshifts","Clunky gearchange feel in Sport","Warning light after repeated incidents","Transmission fault logged in OBD"], repairCostMin:0, repairCostMax:400, diyPossible:false, preventionTip:"Ensure the latest PDK software update has been applied at a Porsche dealer — most covered under warranty." },
    { id:"f2", severity:"Medium", title:"Carbon Ceramic Brake Dust Staining", description:"PCCB discs produce significant black brake dust that stains the centre-lock wheels. The dust can cause corrosion if left on alloy wheels long-term.", affectedYears:"2022–present", frequency:"Very Common", symptoms:["Heavy black dust on wheels after each drive","Brake squeal when cold","Dust embedded in wheel lacquer","Uneven dust distribution front vs rear"], repairCostMin:200, repairCostMax:800, diyPossible:true, preventionTip:"Clean wheels after every track session and apply a ceramic wheel coating to prevent dust bonding to the surface." },
    { id:"f3", severity:"Medium", title:"DRS Wing Rattle at High Speed", description:"The swan-neck rear wing can develop a rattle at sustained high speeds due to DRS mechanism tolerances. Porsche updated the wing mounting bolts in a service bulletin.", affectedYears:"2022–2023", frequency:"Occasional", symptoms:["Rattling from rear above 120mph","Wing movement visible in mirrors","Buzz at certain engine RPM ranges","Creaking over bumps at speed"], repairCostMin:150, repairCostMax:600, diyPossible:false, preventionTip:"Check wing mounting torque at every service and ensure the TSB for updated wing bolts has been carried out." },
    { id:"f4", severity:"Low", title:"Front Splitter Stone Damage", description:"The aggressive front splitter sits extremely low and is easily damaged by road debris, steep driveways, and speed bumps. Carbon fibre repairs are expensive.", affectedYears:"2022–present", frequency:"Common", symptoms:["Visible cracking or chipping on splitter","Scraping on steep driveways","Loose splitter end plates","Aerodynamic imbalance at high speed"], repairCostMin:600, repairCostMax:4500, diyPossible:false, preventionTip:"Use the front axle lift system on steep driveways. Apply PPF to the splitter leading edge before first drive." },
    { id:"f5", severity:"Low", title:"Windscreen Stone Chip Cracking", description:"The raked windscreen angle and track-focused nature means stone chips are very common. The laminated glass is expensive to replace compared to standard 911.", affectedYears:"2022–present", frequency:"Common", symptoms:["Stone chip cracks spreading across screen","Chip in driver eyeline","Failed MOT/inspection","Crack expanding in cold weather"], repairCostMin:800, repairCostMax:2200, diyPossible:false, preventionTip:"Apply a nano ceramic windscreen coating and consider a full-screen PPF film for regular track use or motorway driving." }
  ]
};

export const DEMO_MCLAREN = {
  car: {
    make: "McLaren", model: "720S", year: 2019, trim: "Performance",
    bodyStyle: "Mid-engine coupe", engine: "4.0L Twin-Turbo V8 (M840T)",
    horsepower: 710, torque: "568 lb-ft", transmission: "7-speed SSG dual-clutch",
    drivetrain: "RWD", productionYears: "2017–2023", msrpOriginal: "$299,000"
  },
  parts: [
    { id:"p1", category:"Engine", name:"M840T Twin-Turbo V8 Assembly", partNumber:"MCL-M840T-ASM", description:"4.0L twin-turbocharged V8 producing 710hp. Shares architecture with the P1 hypercar engine and features a flat-plane crankshaft for high-revving performance.", priceMin:65000, priceMax:105000, sources:[{name:"McLaren Dealer",type:"OEM Dealer",priceEstimate:105000},{name:"McLaren Exchange",type:"Independent",priceEstimate:78000},{name:"Used Low Miles",type:"Used/OEM",priceEstimate:65000}], availability:"Special Order", difficulty:"Professional Required", laborHours:28 },
    { id:"p2", category:"Body", name:"Dihedral Door Assembly (Full)", partNumber:"MCL-DOOR-720S-L", description:"Signature McLaren dihedral butterfly door with full glass roof panel. Incredibly complex assembly with integrated glass, seals, and hinge mechanism.", priceMin:8400, priceMax:18000, sources:[{name:"McLaren Dealer",type:"OEM Dealer",priceEstimate:18000},{name:"MSO Direct",type:"Independent",priceEstimate:11500},{name:"Used Panel",type:"Used/OEM",priceEstimate:8400}], availability:"Special Order", difficulty:"Professional Required", laborHours:8 },
    { id:"p3", category:"Suspension", name:"Proactive Chassis Control Hydraulic Unit", partNumber:"MCL-PCC2-720S", description:"McLaren's second-generation Proactive Chassis Control hydraulic suspension unit. Connects all four corners hydraulically for best-in-class body control.", priceMin:4200, priceMax:8800, sources:[{name:"McLaren Dealer",type:"OEM Dealer",priceEstimate:8800},{name:"Hydraulic Dynamics",type:"Independent",priceEstimate:5600},{name:"Used Unit",type:"Used/OEM",priceEstimate:4200}], availability:"Special Order", difficulty:"Professional Required", laborHours:10 },
    { id:"p4", category:"Brakes", name:"Carbon Ceramic Front Disc (390mm)", partNumber:"MCL-CCB-720S-F", description:"390mm carbon ceramic front brake disc providing exceptional fade-free braking from 200mph. Standard on Performance spec, optional on base 720S.", priceMin:3600, priceMax:6200, sources:[{name:"McLaren Dealer",type:"OEM Dealer",priceEstimate:6200},{name:"Carbon Industrie",type:"Aftermarket",priceEstimate:4400},{name:"Used Pull",type:"Used/OEM",priceEstimate:3600}], availability:"Limited", difficulty:"Professional Required", laborHours:4 },
    { id:"p5", category:"Drivetrain", name:"7-Speed SSG Gearbox", partNumber:"MCL-SSG-720S-7", description:"McLaren's Seamless Shift Gearbox dual-clutch unit with near-zero interruption gear changes. Rear-mounted transaxle for optimal 47/53 weight distribution.", priceMin:24000, priceMax:42000, sources:[{name:"McLaren Dealer",type:"OEM Dealer",priceEstimate:42000},{name:"Roush Performance",type:"Independent",priceEstimate:30000},{name:"Exchange Unit",type:"Used/OEM",priceEstimate:24000}], availability:"Special Order", difficulty:"Professional Required", laborHours:20 },
    { id:"p6", category:"Electrical", name:"Vehicle Control Unit (VCU)", partNumber:"MCL-VCU-720S", description:"Central brain of the 720S managing all dynamic systems including AIM, braking, powertrain, and Proactive Chassis Control. Must be programmed to VIN.", priceMin:3800, priceMax:7200, sources:[{name:"McLaren Dealer",type:"OEM Dealer",priceEstimate:7200},{name:"Autronics",type:"Independent",priceEstimate:4900},{name:"Used Coded",type:"Used/OEM",priceEstimate:3800}], availability:"Special Order", difficulty:"Professional Required", laborHours:3 },
    { id:"p7", category:"Cooling", name:"Rear-Mounted Radiator", partNumber:"MCL-RAD-720S-R", description:"One of two side-mounted radiators housed within the rear bodywork. Critical for managing heat from the twin-turbocharged V8 in the tight mid-engine package.", priceMin:1600, priceMax:3200, sources:[{name:"McLaren Dealer",type:"OEM Dealer",priceEstimate:3200},{name:"PWR Performance",type:"Aftermarket",priceEstimate:2100},{name:"Used OEM",type:"Used/OEM",priceEstimate:1600}], availability:"In Stock", difficulty:"Professional Required", laborHours:6 },
    { id:"p8", category:"Exhaust", name:"Centre-Exit Titanium Exhaust Tips", partNumber:"MCL-EXH-720S-TIP", description:"Signature high-mounted centre exit exhaust tips in titanium. The distinctive placement above the rear bumper is a 720S design hallmark.", priceMin:1800, priceMax:3800, sources:[{name:"McLaren Dealer",type:"OEM Dealer",priceEstimate:3800},{name:"Capristo",type:"Aftermarket",priceEstimate:2600},{name:"Used OEM",type:"Used/OEM",priceEstimate:1800}], availability:"In Stock", difficulty:"Moderate", laborHours:2 },
    { id:"p9", category:"Interior", name:"Sport Plus Seat (Carbon Shell)", partNumber:"MCL-SEAT-720S-SP", description:"Lightweight carbon fibre seat shell with electrically adjustable base. Part of the Sport Plus pack, saves 4kg per seat over the standard sport seat.", priceMin:4800, priceMax:9200, sources:[{name:"McLaren Dealer",type:"OEM Dealer",priceEstimate:9200},{name:"MSO Parts",type:"Independent",priceEstimate:6400},{name:"Used OEM",type:"Used/OEM",priceEstimate:4800}], availability:"Limited", difficulty:"DIY Friendly", laborHours:1 },
    { id:"p10", category:"Suspension", name:"Front Upper Wishbone Arm", partNumber:"MCL-WISH-720S-FU", description:"Forged aluminium front upper wishbone for the double-wishbone suspension. The 720S uses double-wishbone at all four corners for precision handling.", priceMin:780, priceMax:1600, sources:[{name:"McLaren Dealer",type:"OEM Dealer",priceEstimate:1600},{name:"Hangar 111",type:"Independent",priceEstimate:1050},{name:"Used OEM",type:"Used/OEM",priceEstimate:780}], availability:"In Stock", difficulty:"Professional Required", laborHours:3 }
  ],
  faults: [
    { id:"f1", severity:"Critical", title:"Hydraulic Suspension Fluid Leak (PCC2)", description:"The Proactive Chassis Control hydraulic system is prone to leaks at the accumulator and interconnecting pipes. Full loss of fluid causes the car to drop to bump stops and become undriveable.", affectedYears:"2017–2021", frequency:"Common", symptoms:["Car sits noticeably lower on one corner","Handling warning light on dashboard","Puddle of orange hydraulic fluid under car","Harsh ride with no damping"], repairCostMin:2800, repairCostMax:7500, diyPossible:false, preventionTip:"Check hydraulic fluid level monthly and inspect the underside pipes for staining. Replace the accumulators proactively at 30,000 miles." },
    { id:"f2", severity:"High", title:"Dihedral Door Seal Failure & Water Ingress", description:"The door seals around the complex dihedral door and roof panel degrade and allow water into the cabin. Water pools in the sill and can damage the VCU and other electronics.", affectedYears:"2017–2022", frequency:"Common", symptoms:["Wet carpet in footwell after rain","Musty smell inside cabin","Electrical gremlins after wet weather","Visible water marks on sills"], repairCostMin:800, repairCostMax:3500, diyPossible:false, preventionTip:"Inspect and replace door seals every 3 years regardless of condition. Apply silicone seal dressing to the roof panel seals annually." },
    { id:"f3", severity:"High", title:"Battery Drain & 12V System Failure", description:"The 720S has a well-documented issue with 12V battery drain when left standing for more than 2 weeks. The complex electronics draw power continuously and can fully discharge the battery.", affectedYears:"2017–present", frequency:"Very Common", symptoms:["Car won't start after short period parked","All screens go blank","Dihedral doors won't open electrically","Battery warning after restart"], repairCostMin:300, repairCostMax:1200, diyPossible:true, preventionTip:"Connect a CTEK battery conditioner whenever the car is stored for more than one week. Never leave it more than 3 weeks without starting." },
    { id:"f4", severity:"Medium", title:"Turbocharger Wastegate Rattle", description:"Both turbochargers can develop a rattle from the wastegate actuator at cold idle. More common on 2017-2019 cars and usually appears under 30,000 miles.", affectedYears:"2017–2020", frequency:"Occasional", symptoms:["Tinny rattling on cold startup","Rattle disappears when warm","Sound from rear of engine bay","Slight boost irregularity in low gears"], repairCostMin:1400, repairCostMax:4200, diyPossible:false, preventionTip:"Allow the car to warm up fully before driving hard. McLaren issued an updated wastegate rod which should be fitted under warranty if still valid." },
    { id:"f5", severity:"Low", title:"Infotainment System Freezing", description:"The IRIS infotainment screen can freeze or reboot unexpectedly, particularly in cold weather. McLaren has released several software updates but the issue persists on older versions.", affectedYears:"2017–2021", frequency:"Common", symptoms:["Screen freezes mid-journey","Navigation loses position","Backup camera doesn't appear","Screen goes black then reboots"], repairCostMin:0, repairCostMax:600, diyPossible:false, preventionTip:"Ensure the latest IRIS software version is installed. Available free at any McLaren dealer and takes about 45 minutes." }
  ]
};

export const DEMO_LAMBORGHINI = {
  car: {
    make: "Lamborghini", model: "Huracán EVO", year: 2020, trim: "EVO",
    bodyStyle: "Mid-engine coupe", engine: "5.2L Naturally Aspirated V10",
    horsepower: 631, torque: "443 lb-ft", transmission: "7-speed LDF dual-clutch",
    drivetrain: "AWD", productionYears: "2019–2024", msrpOriginal: "$261,274"
  },
  parts: [
    { id:"p1", category:"Engine", name:"5.2L V10 Engine Assembly", partNumber:"LAM-V10-HEVO-ASM", description:"Naturally aspirated 5.2L V10 producing 631hp at 8,000rpm. One of the last great naturally aspirated supercars featuring individual throttle bodies and an 8,500rpm redline.", priceMin:58000, priceMax:92000, sources:[{name:"Lamborghini Dealer",type:"OEM Dealer",priceEstimate:92000},{name:"Lamborghini Exchange",type:"Independent",priceEstimate:68000},{name:"Used Low Miles",type:"Used/OEM",priceEstimate:58000}], availability:"Special Order", difficulty:"Professional Required", laborHours:26 },
    { id:"p2", category:"Drivetrain", name:"Haldex AWD Centre Coupling", partNumber:"LAM-AWD-HEVO-CTR", description:"Electronically controlled centre coupling for the Huracán EVO's all-wheel drive system. The EVO adds torque vectoring via the rear E-Diff for superior handling.", priceMin:3800, priceMax:7200, sources:[{name:"Lamborghini Dealer",type:"OEM Dealer",priceEstimate:7200},{name:"Haldex Direct",type:"Independent",priceEstimate:4900},{name:"Used Unit",type:"Used/OEM",priceEstimate:3800}], availability:"Limited", difficulty:"Professional Required", laborHours:8 },
    { id:"p3", category:"Suspension", name:"Magnetic Ride Shock Absorber", partNumber:"LAM-MRC-HEVO-SH", description:"Delphi MagneRide magnetorheological damper unit adjusting stiffness in real-time. Changes damping setting in just 2 milliseconds via magnetic particles in the fluid.", priceMin:1600, priceMax:3200, sources:[{name:"Lamborghini Dealer",type:"OEM Dealer",priceEstimate:3200},{name:"MRC Suspension",type:"Independent",priceEstimate:2100},{name:"Used OEM",type:"Used/OEM",priceEstimate:1600}], availability:"Special Order", difficulty:"Professional Required", laborHours:3 },
    { id:"p4", category:"Brakes", name:"Carbon Ceramic Disc (Front, 380mm)", partNumber:"LAM-CCB-HEVO-F", description:"380mm carbon ceramic front disc with 6-piston Brembo calliper. Optional on standard EVO and standard on the Performante variant.", priceMin:3200, priceMax:5800, sources:[{name:"Lamborghini Dealer",type:"OEM Dealer",priceEstimate:5800},{name:"Brembo OEM",type:"Independent",priceEstimate:3900},{name:"Used Pull",type:"Used/OEM",priceEstimate:3200}], availability:"Limited", difficulty:"Professional Required", laborHours:4 },
    { id:"p5", category:"Exhaust", name:"Titanium Sports Exhaust System", partNumber:"LAM-TI-HEVO-EXH", description:"Full titanium Akrapovic sports exhaust delivering the iconic Huracán V10 scream. Saves 7.6kg and increases sound levels at high RPM.", priceMin:5400, priceMax:9800, sources:[{name:"Lamborghini Dealer",type:"OEM Dealer",priceEstimate:9800},{name:"Akrapovic Direct",type:"Aftermarket",priceEstimate:6800},{name:"Used OEM",type:"Used/OEM",priceEstimate:5400}], availability:"Limited", difficulty:"Professional Required", laborHours:4 },
    { id:"p6", category:"Electrical", name:"LDVI Central Control Unit", partNumber:"LAM-LDVI-HEVO-ECU", description:"Lamborghini Dinamica Veicolo Integrata — the central brain of the EVO managing all dynamic systems including torque vectoring, ABS, and suspension.", priceMin:4200, priceMax:8400, sources:[{name:"Lamborghini Dealer",type:"OEM Dealer",priceEstimate:8400},{name:"Magneti Marelli",type:"Independent",priceEstimate:5600},{name:"Used Coded",type:"Used/OEM",priceEstimate:4200}], availability:"Special Order", difficulty:"Professional Required", laborHours:3 },
    { id:"p7", category:"Body", name:"Forged Composite Front Bumper", partNumber:"LAM-BUMP-HEVO-FR", description:"Lamborghini forged composite (carbon/fibre hybrid) front bumper with integrated splitter and brake cooling ducts. Lighter and stronger than standard fibreglass.", priceMin:4800, priceMax:9600, sources:[{name:"Lamborghini Dealer",type:"OEM Dealer",priceEstimate:9600},{name:"Carbon Works",type:"Aftermarket",priceEstimate:6200},{name:"Used OEM",type:"Used/OEM",priceEstimate:4800}], availability:"Limited", difficulty:"Moderate", laborHours:3 },
    { id:"p8", category:"Cooling", name:"Engine Bay Cooling Fan Assembly", partNumber:"LAM-FAN-HEVO-EB", description:"Engine bay cooling fan pack managing thermal conditions for the mid-mounted V10. Critical in traffic as the naturally aspirated engine generates significant heat.", priceMin:680, priceMax:1400, sources:[{name:"Lamborghini Dealer",type:"OEM Dealer",priceEstimate:1400},{name:"VAG Parts",type:"Independent",priceEstimate:920},{name:"Used OEM",type:"Used/OEM",priceEstimate:680}], availability:"In Stock", difficulty:"Professional Required", laborHours:3 },
    { id:"p9", category:"Interior", name:"Alcantara Steering Wheel (Full)", partNumber:"LAM-STW-HEVO-ALC", description:"Full Alcantara steering wheel with integrated LDVI mode buttons and shift paddles. The flat-bottom design is unique to the EVO generation.", priceMin:1800, priceMax:3600, sources:[{name:"Lamborghini Dealer",type:"OEM Dealer",priceEstimate:3600},{name:"MOMO OEM",type:"Independent",priceEstimate:2400},{name:"Used OEM",type:"Used/OEM",priceEstimate:1800}], availability:"In Stock", difficulty:"DIY Friendly", laborHours:1 },
    { id:"p10", category:"Drivetrain", name:"Rear Electronic Differential (E-Diff)", partNumber:"LAM-EDIFF-HEVO-R", description:"New for the EVO — an electronically controlled rear differential enabling true torque vectoring between rear wheels for sharper cornering.", priceMin:6200, priceMax:11500, sources:[{name:"Lamborghini Dealer",type:"OEM Dealer",priceEstimate:11500},{name:"Gear Works",type:"Independent",priceEstimate:7800},{name:"Used Unit",type:"Used/OEM",priceEstimate:6200}], availability:"Special Order", difficulty:"Professional Required", laborHours:10 }
  ],
  faults: [
    { id:"f1", severity:"High", title:"E-Gear Transmission Sensor Failure", description:"The dual-clutch transmission position sensors are known to fail causing the car to enter limp mode or refuse to select gears. Common on cars used in stop-start city traffic.", affectedYears:"2019–2022", frequency:"Common", symptoms:["Transmission stuck in one gear","Gear selection warning light","Jerky low-speed manoeuvring","Car enters limp mode"], repairCostMin:1800, repairCostMax:4500, diyPossible:false, preventionTip:"Avoid excessive clutch slip in slow traffic. Use manual mode in heavy traffic to reduce heat load on the dual-clutch unit." },
    { id:"f2", severity:"High", title:"Carbon Ceramic Brake Judder After Track Use", description:"The CCB discs can develop thermal hot spots after aggressive track use causing severe brake judder on the road. Requires disc replacement and calliper rebuild.", affectedYears:"2019–present", frequency:"Occasional", symptoms:["Severe pulsing through brake pedal","Steering wheel vibration under braking","Uneven brake pad wear","Visible heat discolouration on discs"], repairCostMin:4500, repairCostMax:14000, diyPossible:false, preventionTip:"Allow 20 minutes of gradual cool-down laps after track sessions. Never apply the handbrake with hot carbon ceramic discs." },
    { id:"f3", severity:"Medium", title:"LDVI Software Conflicts & Warning Lights", description:"The integrated vehicle dynamics control system can log phantom fault codes causing multiple warning lights. Usually a software issue rather than a hardware failure.", affectedYears:"2019–2021", frequency:"Common", symptoms:["Multiple dashboard warning lights simultaneously","ABS and traction control warnings","Suspension fault codes","Systems working normally despite warnings"], repairCostMin:200, repairCostMax:800, diyPossible:false, preventionTip:"Ensure the latest LDVI software version has been installed — Lamborghini released multiple updates addressing false fault codes." },
    { id:"f4", severity:"Medium", title:"Interior Carbon Trim Delamination", description:"The exposed carbon fibre interior trim pieces can delaminate at the edges in hot climates, particularly around the transmission tunnel and dashboard vents.", affectedYears:"2019–2022", frequency:"Occasional", symptoms:["Lifting edges on carbon trim panels","Cracking clear coat over carbon","Trim rattle from loose panels","Discolouration at panel edges"], repairCostMin:600, repairCostMax:3500, diyPossible:false, preventionTip:"Apply UV-protective interior spray to carbon trim panels every 6 months and avoid prolonged parking in direct sunlight." },
    { id:"f5", severity:"Low", title:"AWD Front Driveshaft CV Joint Wear", description:"The front driveshaft CV joints wear prematurely on cars used frequently at full throttle from low speed, causing vibration and clicking on tight turns.", affectedYears:"2019–present", frequency:"Occasional", symptoms:["Clicking noise on full lock turns","Vibration at high throttle low speed","Grease leak at driveshaft boot","Clunking on acceleration"], repairCostMin:800, repairCostMax:2400, diyPossible:false, preventionTip:"Inspect CV boots for cracks at every service. Avoid aggressive launches with the steering at full lock." }
  ]
};

export default DEMO_FERRARI;
